### ISSUE TITLE
User Sign Up

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#117]
We need to allow users to sign up. We can have a popup for google/other provider signup, or a redirect. If we can sign people up by mobile numbers, that would be great.

**Comment by sajmalyousef** [comment]
who should sign up? Both queue creator and user?

**Comment by thehamzarocks** [comment]
As we've discussed before, signing up is crucial in production as relying on auth tokens in local storage has several problems including device lock-in.

At least for the queue creator, signing up should be mandatory as the repercussions could be severe if the creator somehow lost access to the queue he created, affecting several customers.

Instead of taking the user to the create queue page, on clicking create queue queue, he should be redirected to some social signup. If the user is not currently signed in, we can have a small text near the create queue button saying "requires sign-in."

Also we should get rid of the fork-me, at least in production. That would be a good place to put a small circle with the user's photo from google (if google sign-in) or something.

We could also add a sign-up button below the join queue button.

**Comment by daltonfury42** [comment]
I agree with you on everything except making sign up mandatory for creating queues. I'd rather keep it easy to create queue (by not letting sign up come in between), and then remind in a good way somehow that he/she needs to sign up if he wants get more out of the site.

We could write somewhere on the Admin page, something like  "[Sign up](das) to not risk loosing your queues"

We could also make some feature available only to registered features. For example, you have to register (free) if you want to create multiple queues... Or queues will be automatically deleted after 15 days if not created by a registered user.

**Comment by daltonfury42** [comment]
@sajmalyousef Also, for the joiner, absolutely no insistence/need to sign up, but if someone wants to sign up, that should be supported... Also, if you have already signed up with us, maybe because you also manage some queus, we can give extra perks. 

If you are a registered user, maybe we can give extra hidden addons like email notification, and he doesn't have to type name and mobile number again.. but this is tiny tiny features that we can worry about later. What say?

**Comment by nirmalkv** [comment]
I am of the opinion that we should enforce authentication for both creators and clients. Considering the present scenario, queue creators must be keep track all queue participants. Like if a queue participant is tested positive for covid-19, this information will help authorities to track other participants. It can be a usp for the app.

It is a privacy issue though. But we can share the details to the queue creator once the queue is closed, delete it and come out clean.

**Comment by thehamzarocks** [comment]
"Sign up to not risk loosing your queues" - a business uses our app, but doesn't sign up thinking it'll be ok. But if anything goes wrong and he loses his queue, he loses potential customers. When we build applications like this, we must assume users are not very bright and must try to protect them from themselves.

For most businesses, queues are not ephemeral.

**Comment by sajmalyousef** [comment]
We're at user acquisition phase, and at this point I'd say making them sign up acts as a hindrance in trying this app out, by making it compulsory. We can make signing up compulsory if the user wants features like private queue and multiple queues , as part of the retention phase , wherein he likes our product and wants to use it more. I agree with hamza , and maybe we could keep a disclaimer.
As far as signing up for the queue user is concerned sign up using mobile numbers would work, since we're taking they're mobile numbers anyways.

**Comment by nirmalkv** [comment]
Yep that would work, but we have to verify the phone numbers. That is also a kind of authentication right? We can recommend user to sign in in order avoid this again. Govt mandates businesses to keep track of their customers. So say a coffee shop uses our app, they would have to devise another the mechanism to keep track of their customers. My be we should keep default behavior as private queue and let creators choose whether to collect user data. Users should be warned accordingly.

**Comment by daltonfury42** [comment]
Let's tackle all these things step by step. 

For now, think of the **minimal addition to the current app** that allows users to sign up. The question is if we need to enforce registration. People are lazy, 90% people would despise signing up. Let's not force them to sign up.

As for businesses which want to keep track of visitors, your idea is nice, and we should think more and keep it for future. Once we have finished our basic site, next we can take up these add-on features one by one. We would have a queue settings page, where the queue creator can configure all these. He can set in there that joiners have to verify their mobile number to get into the queue.

@thehamzarocks I'll prefer us not forcing the user, but encouraging them to sign up. If they clear their browser cache and loose all the data, it's their mistake. They will  understand and sign up so that it doesn't happen again.

**Comment by daltonfury42** [comment]
https://medium.com/incredible-product-insights/do-you-really-require-users-to-login-signup-for-using-your-app-26ec031485f7

https://www.quora.com/Is-it-better-to-force-a-login-signup-to-use-an-app-or-let-users-use-it-freely-until-they-hit-a-feature-that-requires-a-login

**Comment by thehamzarocks** [comment]
I agree that we need users to be able to evaluate our product before signing up. So let's take this approach:

There should be ample warning when creating the queue. We could do something like changing the text of the button to "Create Temporary Queue" (or something less jarring). And have some info text that says signing up is required for permanent qeueues.

While we could take a different approach than the above, the important thing is to let creators know that their queue is in no way a "reliable" or long-lived one.

And while we're on the topic of spam, we are requiring the mobile number of joiners. Could we come up with a less invasive approach? If the queue isn't a very serious one, mobile numbers shouldn't be required either.

**Comment by daltonfury42** [comment]
Let's create another issue to track the mobile number approach.
