### ISSUE TITLE
[Design] New UI integrate home page and create queue page

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#121]
The beginning page currently does not serve any purpose and should have the functionality same as in create queue link.  Simply move the steps section and text box from 2 to 1
1.
![Screenshot from 2020-07-05 11-37-55](https://user-images.githubusercontent.com/13188906/86526668-7d12db80-beb4-11ea-81cc-860f46e7021c.png)

2.
![Screenshot from 2020-07-05 11-42-14](https://user-images.githubusercontent.com/13188906/86526684-a92e5c80-beb4-11ea-8e5b-0634d43d0708.png)

**Comment by maaverik** [comment]
We designed it this way to have a decent looking homepage with the all the information. Putting create functionality there would bloat the page.

**Comment by sajmalyousef** [comment]
@daltonfury42  what do you think? I find it redundant clicking on create a queue just to go to another page to create a queue
Maybe since the steps are already there below in the home page , just introduce text box here ?

**Comment by akashkbaburajan** [comment]
@sajmalyousef a little bit redundancy is fine as long as the idea and message is conveyed.

**Comment by sajmalyousef** [comment]
Steve Krug in his book "Don't make me think" highlights the following attributes of a usable design

Useful: Does it do something people need done?

Learnable: Can people figure out how to use it?

Memorable: Do they have to relearn it each time they use it?

Effective: Does it get the job done?

Efficient: Does it do it with a reasonable amount of time and effort?

Desirable: Do people want it?

and

Delightful: Is using it enjoyable, or even fun?

Often while designing new experiences, we are so convinced that the new design is so much better than the old one in terms of parameters like effectiveness and efficiency, that we forget that users still have to invest in "learning" the new UX. This is one of the reasons why change, no matter how objectively better, is always viewed with skepticism by the customer.  

This is my line of thought. Adding to this another point is:  I've got close to 50 people to use this and our bounce rate is insanely high ---> implying people just never go past the 1st page (with the old UI). With this 1 more navigation we may further affect our chances of getting people to use it. We can maybe discuss further on call.

**Comment by daltonfury42** [comment]
![image](https://user-images.githubusercontent.com/11256376/86528040-1ac0d780-bec2-11ea-8a4a-a53deae48d68.png)

These are my thoughts,

1) I've hard people say, lesser the click, the better. When discussing UX, they think of it as a huge win to reduce even a single click. But if we needed to have an extra click to make it look good, that compromise can "maybe" be taken.

2) People don't like huge page transitions, minimising those give a good user experience. So maybe if we avoid changing the entire page, that's a plus.

3) But then if we do this, we would have to accommodate the text box in the home page. The stepper can come in the admin page, what's fine. 

Now a proposed solution. Let's take inspiration from the others...

![image](https://user-images.githubusercontent.com/11256376/86528255-d33b4b00-bec3-11ea-96bb-6fe77d02071d.png)


How would it have looked like if google home page required one more extra click to get the search results? Can we also have a single text box and a create / join button? It's signalling to anyone who comes to the joining page that all you need to do to start/join the queue is just one text input, the queue name. (Unlike all other queue management sites)

Think this way, the home page is mainly targeted at the creator. At the current state of the project, joiners would never come here. Who has ever gone to google meet (or survey monkey or but.ly or jit.si) home page and entered the code to join?

**Comment by daltonfury42** [comment]
@akashkbaburajan What do you think?

**Comment by akashkbaburajan** [comment]
I guess this has become a question on why a home page is required.
This was my thought process when I designed home page with two buttons - create and join queue
1. On advertising our app to potential customers, just the home page is enough to make them understand all that our app does. There is an option to create a queue and an option to join a queue. Nothing hidden. Everything intuitive.
2. A potential customer that we would advertise it to would be a queue creator but he would also want to know how people will join his queue. The home page makes that intuitive. No need for any explanation there. If we had gone without home page, his one obvious qn would be how would users join and he will discover share button only if he creates a queue which isn't very obvious.
3. Further enhancement to queue creation logic is made easier here. If in future, we decide to add more inputs in order to create a queue like for eg, queue creators phone number or address or whether it's a Pvt or public queue etc, adding a field here to queue create Page is easier and won't disturb users too much. Cluttering home page won't be a nice idea. 
4. Home page is a good place to showcase features of our product and explanations on how to use the app too.
5. It is as clutter free as possible now with only essential info shown on the screens but making it obvious all the functionalities the application offers.

Contradicting to Nava's point on Google having search text box in home page jtself, google is a search engine and it only has one main functionality, but we got create and join and those who create a queue won't join same queue, so can't keep both together so it'll be either a home page with these two buttons or directly to create queue page.
Also, the sites where users generally don't use the home page, bit.ly etc, doesn't mean they don't have a home page.

But we can maybe have a call and discuss what everyone think. Let's see what Raima has to say too.

**Comment by daltonfury42** [comment]
We are not discussing "why" a homepage is required. The home page, with all its present content is required. The page is still intact with all the things (1, 2, 4, 5) covered.

What I am thinking is, if we add a text box also to it,

```
+--------------------------------------------------+
| Queue Name                                       |
+--------------------------------------------------+

          +--------+          +--------+
          | Create |          |  Join  |
          +--------+          +--------+

```

And that way, we can avoid an extra page.

Regarding queue customisation, I was wondering if we can let the user customise it (point 3) once he created the queue.

**Comment by akashkbaburajan** [comment]
Hmm... That wouldn't be too bad I guess...

**Comment by daltonfury42** [comment]
Covered in new design
