### ISSUE TITLE
[HomePage] Add footer section at the End 

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#212]
![image](https://user-images.githubusercontent.com/11256376/92309837-7c86e600-efc6-11ea-97a5-d0b0b38a6361.png)

https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/

**Comment by MehmetFiratKomurcu** [comment]
Hi @daltonfury42, I'm trying to do this issue, this is how it's looking currently: 
![image](https://user-images.githubusercontent.com/26375064/92330533-25d9e480-f078-11ea-987d-93f836152f95.png)
I wanted to ask that do you have that SimpleQ with people picture svg file, because currently mine is(the one with red square) a screenshot from your design. Thanks.

**Comment by daltonfury42** [comment]
If you go to the design, on the right side there is a `</>` button. When you click on it, all the assets are available on the right pane:

![image](https://user-images.githubusercontent.com/11256376/92330718-bc190500-f08e-11ea-9cf6-81ecb7b66311.png)

You can click on the asset and download the SVG:

![image](https://user-images.githubusercontent.com/11256376/92330731-d521b600-f08e-11ea-8422-79e25993c724.png)

**Comment by MehmetFiratKomurcu** [comment]
Didn't know that feature, thank you!

**Comment by MehmetFiratKomurcu** [comment]
Hey, I need help with this issue.
1- I cant commit because I added an svg images (SimpleQnewlogo) and don't have permission to add new file
2- Have issues with responsiveness (I'm trying to align "open source" and "keep in touch" headers with SimpleQ text, that could be the problem, not sure)

this is the current version: 
![image](https://user-images.githubusercontent.com/26375064/92996730-7dfc6500-f516-11ea-929c-b7ae051efac8.png)
![image](https://user-images.githubusercontent.com/26375064/92996743-966c7f80-f516-11ea-90f0-e25f889feca5.png)

**Comment by maaverik** [comment]
That's weird. What error do you see? Can you post a picture? Does it show up when you try to commit or when you try to push?

**Comment by daltonfury42** [comment]
Hi @MehmetFiratKomurcu you will have to push to your fork, and then raise a PR from there.

Also, in the footer for Gmail, give an anchor `mailto:contact@simplq.me`
For youtube, you can give https://www.youtube.com/channel/UCAb9PSXvrGZ4vvSneK1Nrow 
For Medium: https://medium.com/@raimazach/virtualizing-queues-a-long-overdue-alternative-to-physical-queues-bfdc4b51070f
For Facebook: https://www.facebook.com/simplq/

(You can remove LinkedIn)
