### ISSUE TITLE
[Refactoring][EngDebt] Revisit Storybook

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#277]
We had decided initially to use storybook.js to write reusable components and also fixed on scss for CSS. While using SCSS has turned out to be a right choice, I feel storybook doesn't give us much value addition. It is suitable for larger projects.

We could create a reusable button, but then, that could have been easily done by reusing the css put in a common file.

@maaverik what do you think? Can we remove storybook from our project?

**Comment by maaverik** [comment]
We could. But it wouldn't make much of a difference if we keep it or not. It's a dev dependency I believe so it doesn't slow down the site or anything. And even removing it just means renaming and modifying a few files. I'm fine either way.

**Comment by daltonfury42** [comment]
If we do something, be it a feature, or some framework or some library, and if it's not giving us value, I'd see it as an overhead / eng-debt... I'll remove some day.

It's just adding extra complexity to our codebase which we don't need.

**Comment by maaverik** [comment]
I feel that storybook has its uses. We have more shared components now than before in our common folder and it's starting to become hard to keep track of them. Only a few are currently configured to show up on storybook. I say we integrate all of those with storybook so that new contributors can just run storybook and see all the common components available and choose what they need. The number of common components is only going to go up anyway.
