### ISSUE TITLE
Don't horizontally centre tokens on admin page

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#307]
When a queue is empty, the text `Your queue has been created and is currently empty. Waiting for people to join...` is displayed at the centre:

![image](https://user-images.githubusercontent.com/11256376/95001246-bf4bd600-05e5-11eb-9c25-42b8e7342948.png)

This text is vertically and horizontally centred, which is good. But when tokens are created, they are also centred vertically in the same manner. We don't want this vertical centring:

<img width="1680" alt="Screenshot 2020-10-04 at 2 01 03 AM" src="https://user-images.githubusercontent.com/11256376/95001283-22d60380-05e6-11eb-84c5-719d6c16983a.png">

**Comment by JoaoVSouto** [comment]
I can take this one :smile:

**Comment by karthiksista** [comment]
@JoaoVSouto  I am ready with the PR, if you want to take it you can.

**Comment by JoaoVSouto** [comment]
@karthiksista Oh sorry, there is no problem. You can take it.

**Comment by karthiksista** [comment]
Unable to commit the code due to the **pre-commit hook error, from prettier ** can someone help me out here ?
I am using **node v 12.14.1**

`husky > pre-commit (node v12.14.1)
✔ Preparing...
⚠ Running tasks...
  ❯ Running tasks for *.{js,jsx,ts,tsx}
    ✖ npx prettier --write  [FAILED]
    ◼ eslint --ext .js,.jsx --fix
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up... 

✖ npx prettier --write :
prettier requires at least version 10.13.0 of Node, please upgrade
husky > pre-commit hook failed (add --no-verify to bypass)`

**Comment by karthiksista** [comment]
Unable to commit the code due to error in pre commit check .

I am using node **10.13.0** (also tried with 12.14.1)

This is the error that is being thrown.

**husky > pre-commit (node v10.13.0)**
✔ Preparing...
⚠ Running tasks...
  ❯ Running tasks for *.{js,jsx,ts,tsx}
    ✖ npx prettier --write [FAILED]
    ◼ eslint --ext .js,.jsx --fix
↓ Skipped because of errors from tasks. [SKIPPED]
✔ Reverting to original state because of errors...
✔ Cleaning up... 

**✖ npx prettier --write:
prettier requires at least version 10.13.0 of Node, please upgrade
husky > pre-commit hook failed (add --no-verify to bypass)**

Can anyone help me out?

**Comment by daltonfury42** [comment]
For some reason prettier is not picking up the node version. Are you using `nvm`?

You can bypass pre commit checks for now by adding `--no-verify` to you commit command.

**Comment by karthiksista** [comment]
@daltonfury42 Thanks for the reply, yes i am using nvm. 
Yes, tried with `--no-verify`. Its working.
But was curious on why prettier was not picking up the node version.

Here is the [PR](https://github.com/SimplQ/simplQ-frontend/pull/312) for this issue.

**Comment by daltonfury42** [comment]
I don't use nvm much, so can't say why it's picking the right version. Thanks for the PR!
