### ISSUE TITLE
Tweak Home page layout

### ISSUE THREAD

**Issue by akashkbaburajan** [SimplQ/simplQ-frontend#323]
1. The curved div is rather too curved as compared to design.
2. The the text along with buttons can come a little more down kinda like centre of page
3. There is too much space between curved line beginning and "Why SImplQ" section heading.
refer design to see what is expected - https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/
![Adobe XD 04-10-2020 11_45_18 (2)](https://user-images.githubusercontent.com/16539463/95010490-6876e880-0647-11eb-8f29-37e1593fdf98.png)

**Comment by daltonfury42** [comment]
1) The curved div was an approximation. Can you somehow export/provide the SVG from XD? The current svg was generated by playing with https://getwaves.io/ for a ling time :p hence it's an approximation

2) Let me make that quick change, or do you want to do that to get your hactober tshirt?

3) I've been noticing a lot of modern websites recently, and they have a lot of whitespace.  I'm of the opinion that Why SimplQ has the right amount of whitespaces:

![image](https://user-images.githubusercontent.com/11256376/95011051-9827ef80-064b-11eb-9b6f-3bf046bb2d1e.png)

but the further sections are crammed:

![image](https://user-images.githubusercontent.com/11256376/95011065-ab3abf80-064b-11eb-8d81-e5b3787cccd8.png)


What do you think?

**Comment by akashkbaburajan** [comment]
1. I have updated the design to make that div exportable. Maybe that'll help make website similar to design
2. You can do it :)
3. Compared to spaces in other sections, "Why SimplQ" section has too much space. I am of the opinion that we should make spacing consistent in all sections.
4. Those images of corona can be spread across a little better, like maybe in the design. (I didn't really like the last one at the bottom)

**Comment by daltonfury42** [comment]
1. The assets are not available in the design. https://xd.adobe.com/view/ad1db074-03bf-45b1-537b-98d9d524ec82-db2c/specs/

I wanted just the top curve div is this somehow possible? 

![image](https://user-images.githubusercontent.com/11256376/95012032-e2f93580-0652-11eb-9158-ed9cdf638579.png)

2. Ok

3. Let's increase spacing in the three sections following Why SimplQ. I think footer is fine. (Let me know if this is not fine)

4. Corona images are a bit tricky, we can try. I have to position them absolutely, and then it should not ovelapp on smaller screens. That's why I placed those like that.

**Comment by akashkbaburajan** [comment]
1. yep, I am updating the design so you can get a similar svg
3. awesome
4. haa.. its tricky huh ..hmm its fine then

**Comment by gabrielatricak** [comment]
Hi i would like to work on this issue for school project. Can I be assigned to this?

**Comment by daltonfury42** [comment]
Sure please do. @gabrielatricak
