### ISSUE TITLE
Icon background on navbarcan be transparent

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#358]
The background of the icon is white and its visible on mobile . It does'nt make sense when navbar itself is white and looks odd
@akashkbaburajan 
![lollol](https://user-images.githubusercontent.com/13188906/95168364-d0a40680-07ce-11eb-9883-398c6e405b8d.jpg)

**Comment by daltonfury42** [comment]
This is happening because the image happend to have a z-index greater than that of the overlay (the grey fade giving div)

https://github.com/SimplQ/simplQ-frontend/blob/7d3141cb6a555a770b82fa94ef67420f4c586cc4/simplq/src/styles/logo.module.scss#L6

Lets fix this. Try removing the zindex defined above.

**Comment by daltonfury42** [comment]
@maaverik If that z-index is not intentional, let's remove?

**Comment by maaverik** [comment]
The z-index is intentional. The reason is, without it, parts of the navbar cover the simplq text and prevents it from scrolling to top on clicking the text. This is not a big deal though. Clicking the logo was working fine for the scroll, so the z-index can be removed since the issue mentioned here is higher priority.

**Comment by daltonfury42** [comment]
I see, I think it's because navbar has a z-index of 99 and all. We should fix z-indexes.. I'm not an expert but this is what I could think of:

Navbar's z-index: x;
image's z-index: x+1;
overlay's z-index: x + 2
side drawer's z-index: x+3;

where x greater than z-index of other items on the page. We need to fix these values at one go. Shall we mark it as "You can do this" - Fix z-indexes?

**Comment by maaverik** [comment]
"You can do this" is fine. Best not to mark it as "good first issue" since it requires some experience with frontend to get done perfectly.

**Comment by icy-meteor** [comment]
Would like to contribute to this issue.
If you could explain me a bit more in detail on what we are trying to achieve here because as @daltonfury42 said , z-index:10 on the logo seems to be the issue. I didn't quite get what you were trying to say @maaverik.

**Comment by daltonfury42** [comment]
The requirements are:

1. The navbar should be constantly present on top and above all the contents of the screen when user scrolls down. (So it should have higher z-index than other components.
2. When in mobile / smaller screens, clicking on the burger menu brings the sidebar (and an overlay which dims the background), and it should above the navbar. 

Currently the logo has a z-index higher than the overlay, so it's standing out. This is the bug. Play with the z-indexes of the components of the page so that this behaviour works. 

Just make sure that clicking on the logo (the logo is an independent component) would take the user to the top of the page.

**Comment by icy-meteor** [comment]
Right, this helps. Thanks.
Also, clicking the logo should take them to the top, but this wont be possible on mobile devices when sidebar is open. Am I right? This is because sidebar would take a higher priority and dim things outside of it and clicking anywhere outside would just close the sidebar.

**Comment by daltonfury42** [comment]
correct

**Comment by devashishpuri** [comment]
Hi! Raised a PR for this

https://github.com/SimplQ/simplQ-frontend/pull/360

**Comment by icy-meteor** [comment]
@daltonfury42 @maaverik 
Ideally, if you see from a product and UX perspective, having the logo as clickable when sidebar is open is a flawed user experience. 
If we remove the z-index:10 from logo, it fixes everything according to me. 

1. Navbar is already fixed and it is retained while scrolling, so I don't have to touch that.
2. In mobile, the sidebar is already above the navbar, which is also working, so I don't have to touch that.
3. Clicking on the logo is scrolling to the top as intended (except for when sidebar is open in mobile), which is absolutely correct behaviour.

The reason for this is that sidebar takes away user's attention into a separate entity on the screen by dimming the surroundings. The expected behaviour as per human psychology is that when someone clicks away from the sidebar, irrespective of where he/she clicks, it should collapse the sidebar. And this seems to be working correctly.

Let me know if you have any doubts here, we can discuss further if needed.
For now, I have raised the PR with the z-index fix.

**Comment by daltonfury42** [comment]
@maaverik can you take a look? The a move makes sense to me.

#361

**Comment by maaverik** [comment]
I agree with you @icy-meteor. I guess my earlier comment wasn't clear enough. The reason I added the z-index was because the logo component in its entirety wasn't clickable on the desktop due to the navbar overlapping.

![Screenshot from 2020-10-06 22-40-37](https://user-images.githubusercontent.com/12583528/95236871-1b506d80-0825-11eb-809d-3c4a90756e29.png)

Removing the z-index brings back that problem which is not a big deal, but it is what it is. Ideally, we would want to fix the navbar overlapping. The z-index wasn't the right solution.

**Comment by daltonfury42** [comment]
I take it back. @maaverik has a point...
@icy-meteor Try removing the zindex a part of the text becomes unclickable.

Sorry!!

**Comment by devashishpuri** [comment]
Addressed the same in my PR. Played around with z-indexes in mobile view.

**Comment by maaverik** [comment]
It looks like both the open PRs #361 and #360 work. I prefer #361 since it solves the core problem.
