### ISSUE TITLE
Join Queue not working

### ISSUE THREAD

**Issue by sajmalyousef** [SimplQ/simplQ-frontend#365]
**Describe the bug**
Join Queue button does not work in the join queue page

**To Reproduce**
1. Go to https://simplq.me/j/AbcQueue
2. Click on Join Queue.'
3. not able to join

**Expected behavior**
User should be able to join AbcQueue

**Screenshots**

![image](https://user-images.githubusercontent.com/13188906/95425853-8e133300-0962-11eb-86b9-3826320fa0b9.png)

**Comment by maaverik** [comment]
This is very interesting. Enter press works all the time even though enter press and the button click trigger the same function. Also, the button click when I have the dev tools window open and if not, the button click doesn't do anything.

**Comment by sajmalyousef** [comment]
Why is the button not clickable?

**Comment by maaverik** [comment]
It's a styling issue. Another div covers the button, that's why the dev tools window fixes it. I never thought something like this could occur.

![Screenshot from 2020-10-08 22-10-50](https://user-images.githubusercontent.com/12583528/95488476-3b159c00-09b3-11eb-9ead-8a770981aedb.png)

I'll check this sometime soon.

**Comment by maaverik** [comment]
I think a z-index might be the easiest fix. @daltonfury42 what do you think?

**Comment by maaverik** [comment]
#366

**Comment by sajmalyousef** [comment]
This has been fixed

**Comment by maaverik** [comment]
Check if #366 looks okay. I think there aren't any more problems.
