### ISSUE TITLE
Add an option to create a new queue/ entering new code if no queue by that code exists

### ISSUE THREAD

**Issue by HJain13** [SimplQ/simplQ-frontend#422]
**Is your feature request related to a problem? Please describe.**
I was just trying it out, and instead of clicking create button, clicked join button; 404 came up

**Describe the solution you'd like**
While 404 is serviceable, A page explicitly mentioning a queue doesn't exist and prompting to either create one or enter a new code might be a better UX

**Comment by maaverik** [comment]
Adding a prompt to create a queue wouldn't be the best idea since people who want to join a queue wouldn't want to create one. In case they clicked mistakenly, they can go to the home page. But a page specifically saying that the entered queue doesn't exist and having an option to enter another queue name to join would be good. 

Or, more easily, we could modify the navigation to just show the popup saying the entered queue doesn't exist instead of trying to go to the join page. The same thing that happens when someone tries to create a queue that already exists. This way, users wouldn't have to keep going back and forth between pages in case of mistakes. 

@daltonfury42 what do you think?

**Comment by daltonfury42** [comment]
This is what happened: @HJain13 wanted to try out SimplQ, so he entered a new queue name, and unconsciously clicked on the Join queue button instead of create queue. We served him 404 page, and since he made this mistake unconsciously, he is now wondering if the site is down.

![image](https://user-images.githubusercontent.com/11256376/101497233-c2ba5f80-3990-11eb-864a-edf76d96ab73.png)

Better UX is to handle this situation by, rather than saying "404, ERROR", tell him that the queue he tried to join does not exist, and ask if he wants to create a queue with the entered name instead. This is slightly better UX. Even if user unconsciously made a mistake, we should handle it smoothly, when possible.

**Comment by daltonfury42** [comment]
Rough idea, instead serve this in such scenarios:

![image](https://user-images.githubusercontent.com/11256376/101498686-67896c80-3992-11eb-992c-fbd5a254dc4e.png)

**Comment by AleemRehman** [comment]
@daltonfury42 I can pick this up?

**Comment by daltonfury42** [comment]
Sure. What solution do you have in mind? Simplest way that I could think of is to check from the 404 page component if the url matches the regex `/j/[A-Za-z0-9-]*$` if yes, render different text.

It might be a good idea to build the regex in one place inside [this](https://github.com/SimplQ/simplQ-frontend/blob/master/simplq/src/components/common/utilFns.js#L7) file and reuse. What do you think?

**Comment by AleemRehman** [comment]
That sounds like a good solution, will get to work proofing that out @daltonfury42

**Comment by prabureddy** [comment]
> Rough idea, instead serve this in such scenarios:
> 
> ![image](https://user-images.githubusercontent.com/11256376/101498833-91db2a00-3992-11eb-81f4-478c49f7cc31.png)

What is the difference of adding these above two buttons? Both the button in this above page will redirect the user the same page right? If not where will the user land if they click these two buttons?

**Comment by daltonfury42** [comment]
Create Queue will create the queue and take him to the admin page. Return home goes to home page.

**Comment by prabureddy** [comment]
But where will he write the queue name to create queue? Do we have to create a text box on this page?

**Comment by daltonfury42** [comment]
Best is to have a text box and pre-fill it with the queue name he had entered in the previous screen. The name he had entered while in the home page, that got him to this page. 

But if we are going that route, we would want to somehow refactor out the [CreateJoinForm](https://github.com/SimplQ/simplQ-frontend/blob/master/simplq/src/components/pages/Home/CreateJoinForm.jsx) from home page into common folder and reuse it here. What do you think?

**Comment by maaverik** [comment]
Prefilling a text box is a good idea. How about also having a join queue button here? Someone could end up in this page if they misspelled their intended queue name. This way, they can modify and try again with ease. So essentially the whole CreateJoinForm can be reused like you said without having to make any changes to it.

**Comment by daltonfury42** [comment]
Agreed, this is better.
