### ISSUE TITLE
Problems with header logo on privacy policy page

### ISSUE THREAD

**Issue by Vigenh199** [SimplQ/simplQ-frontend#447]
**Is your feature request related to a problem? Please describe.**
A  SimplQ header logo isn't showing fully on [simplq.me/privacy](https://simplq.me/privacy)

**Describe the solution you'd like**
I want to add a space between logo and navbar.

**Describe alternatives you've considered**
I've not considered any alternatives.

**Additional context**
![privacy logo issue](https://user-images.githubusercontent.com/76869499/103651977-d5b65480-4f7b-11eb-97f3-c13601184532.png)

**Comment by daltonfury42** [comment]
Hi @Vigenh199 thanks for pointing this out. Our Navbar has a fixed height of `4rem` so the easiest fix is to add a `margin-top: 4rem` to the header section.

But I want to take a slightly better approach as use padding and increase the min-height instead, so that in case the navbar does away in the future, the void won't be filled with blank margin space.
