### ISSUE TITLE
Spinners modify page styles when active

### ISSUE THREAD

**Issue by maaverik** [SimplQ/simplQ-frontend#475]
**Is your feature request related to a problem? Please describe.**
Many of our components use the flex-wrap CSS tag which makes them expand or shrink based on child components. I think because of this, the [LoadingIndicator](https://github.com/SimplQ/simplQ-frontend/tree/master/simplq/src/components/common/LoadingIndicator) component ends up changing the page styles whenever active. e.g.,

![Peek 2021-01-17 01-08](https://user-images.githubusercontent.com/12583528/104821250-8ff16a00-5860-11eb-8268-52fd441e41e7.gif)

**Describe the solution you'd like**
Modify the LoadingIndicator component so that it's parent component does not expand or shrink unnecessarily.

**Comment by mathkruger** [comment]
Hi! I tried to simulate this error and I found out that the problem is not exactly with the LoadingIndicator component. I removed it in this screen and the problem is still there.

I believe the problem is with the two buttons that disappear when clicking in the button "Create Queue". I can solve this by creating a div that wraps the buttons and add this css code into it when the "createInProgress" variable is true: `opacity: 0; pointer-events: none;`.
