### ISSUE TITLE
Implement PWA A2HS functionality

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#595]
We aim to be a PWA, it's mostly there, we need to see whatever is left to do. One thing to do is A2HS, explained [here](https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen).

**Comment by eric-santos** [comment]
I figured out how to make it a PWA but I'm having trouble committing or pushing due to husky hooks on package.json. I found a workaround by doing npm run lint. It seems to only happen on windows computers. https://github.com/typicode/husky/issues/716, is there a workaround you may have seen before? Or is it ok to push with that?

**Comment by shiv15** [comment]
Is anyone working on this? Can I pick this up?
