### ISSUE TITLE
UX and Flow Improvements - Draft List

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#621]
1. My Queues doesn't stand out and people will miss it.
2. Scan the QR code takes you to the join page. Join page should have an option to enter the number. If the person is already in the queue, take to the token status page for him. (Self join should be disabled by default, configurable)
3. QR should be present already generated on the admin page than hidden behind a button.

**Comment by maaverik** [comment]
For the india-fights-back branch:

Are you hospital or vaccine center? Start by createing queue:  -> Are you a hospital or vaccine center? Start by creating a queue:

No more crowd at vaccine centers. -> No more crowds at vaccine centers.

Ask them to wait outside without crowding in front of the vaccine . -> Ask them to wait outside without crowding in front of the vaccine centre

Token number can be send via SMS -> Token number can be sent via SMS

Join a queue without crowd -> Join a queue without crowding

When you react the vaccine center, give your mobile number to get into the queue. -> When you reach the vaccine center, give your mobile number to get into the queue.

Waiting for the staff to call you when your turn in near -> Wait for the staff to call you when your turn is near

Check your token status in queue and get notified when your turn is up -> Check your token status in the queue and get notified when your turn is up

Make free pricing say Rs instead of $

**Comment by sajmalyousef** [comment]
Two thoughts:

1.  I may join multiple queues without going to the center . How to address this?
2.  Since this is entirely free. Identity verification might be an issue. Cowin app does aadhar verification. Can the vaccine center allow/reject a person to the queue based on some list they might have?

**Comment by daltonfury42** [comment]
(1) is a real problem. Been thinking about it, and also from a general crowd control perspective. So I am thinking of keeping self-join disabled by default. In the proposed new flow, the queue manager would scan generate the QR code and put it all around the vaccination centre. 

**Flow 1: Default**
1. The queue manager adds the person manually to the queue by asking for his name and contact number. 
2. He would tell the person to wait outside, and to check the status via QR or link send my SMS (SMS will be enabled manually for accounts of covid vaccination centres and hospitals enrolled with us).
3. When the user scans the QRs, it will ask for his mobile number and take him to the token status page.

**Flow 2: Self Join enabled**.
If the admin wants to let people join own their own via the queue link / QR, it will be a configurable queue setting. If admin has enabled "Self Join", upon scanning the QR, it will ask for mobile number as usual. If the mobile number is already in the queue, he will be taken to the token status page, else he will be asked his name, and he can join.

(2) For vaccination centres, verification is a separate concern that is already taken care of by their systems. We don't have to do it.

(3) Even with the slot, people will come and crowd in front of the vaccine centre. To keep these people in a socially distant manner, SimplQ can be used.

**Comment by PavanDongare** [comment]
@sajmalyousef 
1 by calling center. Adding to queue will be allowed only by admin
2 handled by centers

**Comment by sajmalyousef** [comment]
(2) In Flow 2 would having this similar to google meet add value ? This can help self join as well. It should help center handle unregistered entry into the queue. Outside the ones registered for the slot 
![image](https://user-images.githubusercontent.com/13188906/115853922-53c53b00-a447-11eb-8dce-05ffd3d76565.png)

(3) Understood that SimplQ's purpose is different. It was more on the confusion multiple tokens could create

**Comment by daltonfury42** [comment]
Yeah it's a good idea. We can build that out as a configuration once basic flow 2 is done.

**Comment by daltonfury42** [comment]
Adding a self join flag and setting it to disabled by default is a significant change. Till now we were telling, "Share the link to join the queue", this would change to "Users can visit the link to know their token status" as the default product behaviour. cc @maaverik
