### ISSUE TITLE
System Notification Alerts

### ISSUE THREAD

**Issue by daltonfury42** [SimplQ/simplQ-frontend#94]
Websites can send notification through the browser to the OS:

![image](https://user-images.githubusercontent.com/11256376/84309538-e0dc0a00-ab7d-11ea-90bd-7dd4e8457aa6.png)
The same code should hopefully work on mobile.

We would have to politely ask the user to enable notifications from our site. Then the queue status can be pushed to the joiner better.

**Comment by thehamzarocks** [comment]
There are two parts to this: requesting permission to show notifications and actually sending them.

1. Permissions - A good practice is only requesting permission in response to a user event. One good place would be to have an enable notifications button where the joiners are waiting to get notified. This would prevent annoying popups to visitors of the site who might simply end up disabling them.

2. Sending notifications - will need to dig further into this, but ideally the notification should be shown to the joiner when the creator clicks the notify button. (Also the last step of the stepper should not be named wait to get notified since the user is already notified. Instead, it should be something like you're in!)

**Comment by daltonfury42** [comment]
Yes, an enable system notification button would make it being asked on the user's request, and hence he would be more likely to grant permission. We should keep the button in a nice spot so that people will see it. 

Would you like the get a system notification when your turn comes? (Yes button)

But let's explore the notification capability first and then think on a smart place to place this. And also this task in dependent on #41. So you want to take it up first?

The stepper can be changed.

**Comment by maaverik** [comment]
https://www.youtube.com/watch?v=ggUY0Q4f5ok

This might be helpful

**Comment by thehamzarocks** [comment]
Since we are currently not using push notifications, we would have to rely on the application running in some window on the browser to be able to view notifs.

If we want to be able to notify the user no matter which page of the app he's currently in (even homepage), then we need to be able to detect notify status throughout the UI.

If we require the queue status page to be left open, then we can write this logic in that particular component.

However, if we need to display notifs even if the app is closed, we'll need to rely on push notifications.

Would love to hear your thoughts on this.

**Comment by maaverik** [comment]
We can't really be expected to provide notifications when the app is closed since ours is a web app after all, so there's no need to think about supporting that, at least for the near future. As for displaying notifications no matter what page the user is on, there might be a way to do that using the service workers. We have this file simplq/src/serviceWorker.js which I intended to enable once the dev work is done so that we get some caching for assets. I haven't read much on this yet, but I believe it's made to support things like notifications. Let's research more on this and decide how to handle this issue.

**Comment by daltonfury42** [comment]
I second that. Let's get a simple notification system implemented where you get notified only if you are on the status page. 

Service workers idea looks interesting, we can explore that in a follow up PR or whenever anyone is interested in picking it up.
